Implement version field type
elastic/elasticsearch-net pull request #5200
Opened 2020-12-18 07:25 UTC by stevejgordon

@Mpdreamz I've attempted this by reviewing previous PRs and a bit of sleuthing! Please let me know if I've missed anything. I've been able to use the mapping on a test project.

Main challenge in naming in `FieldCapabilities` since that already has the concept of the "_version" field. I welcome opinions on the naming. Perhaps in 8.0 we can consider renaming both of these so that `Version` becomes `DocVersion`?

2020-12-28 14:26 UTC, Mpdreamz requested changes
Almost there one failing test on parity:

```
[xUnit.net 00:00:24.7659600]     Tests.Mapping.PropertyDescriptorTests.IPropertiesDescriptorImplementsAllPropertyMethodsOfPropertiesDescriptor [FAIL]
  Failed Tests.Mapping.PropertyDescriptorTests.IPropertiesDescriptorImplementsAllPropertyMethodsOfPropertiesDescriptor [25 ms]
  Error Message:
   Expected concreteMethodNames.Except(interfaceMethodNames) to be empty, but found {"Version"}.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Execution.GivenSelector`1.FailWith(String message, Object[] args)
   at FluentAssertions.Execution.GivenSelector`1.FailWith(String message, Func`2[] args)
   at FluentAssertions.Collections.CollectionAssertions`2.BeEmpty(String because, Object[] becauseArgs)
   at Tests.Mapping.PropertyDescriptorTests.IPropertiesDescriptorImplementsAllPropertyMethodsOfPropertiesDescriptor() in D:\a\1\s\tests\Tests\Mapping\PropertyDescriptorTests.cs:line 42
```


`FieldTypes.Version` is indeed a conundrum. Don't think a clean option exists. ++ to `DocVersion` in 8 for `_version`.

2020-12-30 08:48 UTC, stevejgordon commented
Thanks @Mpdreamz. I've fixed up the interface causing the failure. Will allow the tests to run in CI and then merge if that's all good.

2021-01-06 18:09 UTC, Mpdreamz requested changes

2021-01-06 18:09 UTC, Mpdreamz commented on tests/Tests/Mapping/Types/Specialized/Version/VersionPropertyTests.cs
> +	public class VersionPropertyTests : PropertyTestsBase
`SkipVersion` other then that LGTM

2021-01-07 13:17 UTC, merged