[DOCS] Removes low-level client docs and references
elastic/elasticsearch-net pull request #6188
Opened 2022-03-24 15:44 UTC by szabosteve

## Overview

This PR removes the low-level client-related documentation pieces from .NET docs and also deletes the references to that book from the rest of the docs pieces.

2022-03-24 16:25 UTC, szabosteve commented
@elasticmachine test this please

2022-03-25 08:14 UTC, stevejgordon requested changes
One note about a removal I don't think we need. Otherwise LGTM thanks!

The naming for some of the types needs updating but I can follow up with a PR to start correcting those as necessary.

2022-03-25 08:14 UTC, stevejgordon commented on docs/client-concepts/connection-pooling/building-blocks/connection-pooling.asciidoc
> +instance of `ConnectionSettings`.
I think we want to leave in the note about the lifetime of the pool here.

2022-03-25 09:26 UTC, stevejgordon approved these changes
Thanks!

2022-03-25 09:46 UTC, merged