[DOCS] Update scrolling document.asciidoc
elastic/elasticsearch-net pull request #6409
Opened 2022-05-13 12:43 UTC by salihklc

adding more detail to example code

2022-05-13 12:44 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2022-05-13 13:58 UTC, stevejgordon requested changes
Thanks @salihklc for the suggestion. Unfortunately the docs process is quite complex right now. We're reworking the docs for v8 once that client is closer to GA. This change is best targeted at the 7.17 branch please.

Additionally, we generate the AsciiDoc file from [here](https://github.com/elastic/elasticsearch-net/tree/master/src/Tests/Tests/Search/ScrollingDocuments.doc.cs), so this change would need to be made in that source file and then the docs generator can be run from the command line using `.\build.bat documentation` which produces the asciidoc.

Is that something you're willing to take on? If so, once generated I can port the changes (if applicable) to the v8 documentation as part of that process.

If you're unable to do this locally, that's also fine and I can tackle it locally and close out this PR. Just let me know.

2022-05-13 13:58 UTC, stevejgordon commented on docs/search/scrolling-documents.asciidoc
> +<3> do something with the response, (Client search request also return the first iteration of query)
I'd recommend we make this:
```
<3> Do something with the response (which includes the first "page" of results).
```

2022-05-13 14:04 UTC, salihklc commented on docs/search/scrolling-documents.asciidoc
> +<4> Get next page scroll response and set it to searchReponse to use it on ProcessResponse
🥳

2022-10-19 09:39 UTC, stevejgordon commented
Thanks for your contribution, @salihklc. I will close this PR as we're reworking the 8.0 documentation significantly.

2022-10-19 09:39 UTC, closed without merging